### ISSUE TITLE
代码块高亮功能失效

### ISSUE THREAD

**Issue by KeyToLove** [miiiku/hexo-theme-flexblock#47]
如题，从默认主题`landscape`切换至`flex-block`主题代码块高亮失效了，默认主题下代码高亮是正常的，需要额外配置什么吗？

**Comment by KeyToLove** [comment]
从默认主题下`hexo generate`生成的`css/style.css`中copy代码高亮部分代码，然后在主题`layout.ejs`中引入后暂时解决了高亮失效的问题
其中copy的`highlight.css`文件内容为:
```css
pre .comment,
pre .title {
  color: #999;
}
pre .variable,
pre .attribute,
pre .tag,
pre .regexp,
pre .ruby .constant,
pre .xml .tag .title,
pre .xml .pi,
pre .xml .doctype,
pre .html .doctype,
pre .css .id,
pre .css .class,
pre .css .pseudo {
  color: #f2777a;
}
pre .number,
pre .preprocessor,
pre .built_in,
pre .literal,
pre .params,
pre .constant {
  color: #f99157;
}
pre .class,
pre .ruby .class .title,
pre .css .rules .attribute {
  color: #9c9;
}
pre .string,
pre .value,
pre .inheritance,
pre .header,
pre .ruby .symbol,
pre .xml .cdata {
  color: #9c9;
}
pre .css .hexcolor {
  color: #6cc;
}
pre .function,
pre .python .decorator,
pre .python .title,
pre .ruby .function .title,
pre .ruby .title .keyword,
pre .perl .sub,
pre .javascript .title,
pre .coffeescript .title {
  color: #69c;
}
pre .keyword,
pre .javascript .function {
  color: #c9c;
}
```
请教一下是不是我的使用方式有问题，才导致了默认配置下代码高亮失效

**Comment by miiiku** [comment]
看一下`config.highlight.enable`这个属性是否打开的，如果没有开启，是不会加载高亮代码相关的css和js的

**Comment by miiiku** [comment]
这是我demo网站的config配置信息，你可以对着看一下哪里没配置对；

https://github.com/miiiku/flexblock-example-site/blob/master/_config.yml#L41

**Comment by KeyToLove** [comment]
> 这是我demo网站的config配置信息，你可以对着看一下哪里没配置对；
> 
> https://github.com/miiiku/flexblock-example-site/blob/master/_config.yml#L41

cool~ ，`highlight`配置下`hljs`属性 hexo初始化的时候是`false`，改成`true`解决了该问题

before
```yml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```
after
```yml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
```
