### ISSUE TITLE
博客封面

### ISSUE THREAD

**Issue by abinzzz** [miiiku/hexo-theme-flexblock#68]
每个博客的封面该怎么加呢？求助

**Comment by seeleclover** [comment]
在每篇 post 文章的 front-matter 中配置 cover 字段，就可以单独给文章配置封面了。

以下是 post 文章的 front-matter 配置示例：

```yaml
title: {{ title }}
date: {{ date }}
updated: {{ date }}
cover: 
categories: 
tags: 
toc: true
comments: true
aplayer: false
dplayer: false
mathjax: false
```
