### ISSUE TITLE
大佬请问我使用flexblock主题，渲染出来的代码有高亮功能，但是没颜色怎么破

### ISSUE THREAD

**Issue by cardchoosen** [miiiku/hexo-theme-flexblock#84]
### _config.yml里面我配置了
```javascript
syntax_highlighter: highlight.js
highlight:
  enable: true
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  line_threshold: 0
  tab_replace: ''
```
### vscode预览
<img src="https://github.com/miiiku/hexo-theme-flexblock/assets/32973891/766d1f53-4ffc-4ed0-900e-05b504bc5adf"  width="500">

### 网页浏览，有行号和复制按钮，有高亮但是没颜色qaq
<img src="https://github.com/miiiku/hexo-theme-flexblock/assets/32973891/a0453aed-79fa-4abd-83e5-a84cc8352b68"  width="500">

**Comment by L33Z22L11** [comment]
`_config.yml`

```yaml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: true
  theme: atom-one-dark # 主题列表: https://highlightjs.org/demo
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""
```
